export const sales = [
    {
        Date: "1/1/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 84.63,
        Quantity: 10,
        Payment: "Credit card",
        cogs: 846.3,
        Rating: 9.0,
    },
    {
        Date: "1/1/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 63.22,
        Quantity: 2,
        Payment: "Cash",
        cogs: 126.44,
        Rating: 8.5,
    },
    {
        Date: "1/1/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 74.71,
        Quantity: 6,
        Payment: "Cash",
        cogs: 448.26,
        Rating: 6.7,
    },
    {
        Date: "1/1/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 36.98,
        Quantity: 10,
        Payment: "Credit card",
        cogs: 369.8,
        Rating: 7.0,
    },
    {
        Date: "1/1/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 27.04,
        Quantity: 4,
        Payment: "Ewallet",
        cogs: 108.16,
        Rating: 6.9,
    },
    {
        Date: "1/1/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 65.74,
        Quantity: 9,
        Payment: "Cash",
        cogs: 591.66,
        Rating: 7.7,
    },
    {
        Date: "1/1/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 47.59,
        Quantity: 8,
        Payment: "Cash",
        cogs: 380.72,
        Rating: 5.7,
    },
    {
        Date: "1/1/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 72.61,
        Quantity: 6,
        Payment: "Credit card",
        cogs: 435.66,
        Rating: 6.9,
    },
    {
        Date: "1/1/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 62.87,
        Quantity: 2,
        Payment: "Cash",
        cogs: 125.74,
        Rating: 5.0,
    },
    {
        Date: "1/1/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 21.12,
        Quantity: 8,
        Payment: "Cash",
        cogs: 168.96,
        Rating: 6.3,
    },
    {
        Date: "1/2/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 58.23,
        Quantity: 3,
        Payment: "Ewallet",
        cogs: 174.69,
        Rating: 8.2,
    },
    {
        Date: "1/2/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 45.0,
        Quantity: 5,
        Payment: "Credit card",
        cogs: 225.0,
        Rating: 7.4,
    },
    {
        Date: "1/2/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 89.99,
        Quantity: 1,
        Payment: "Cash",
        cogs: 89.99,
        Rating: 9.1,
    },
    {
        Date: "1/2/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 55.66,
        Quantity: 7,
        Payment: "Credit card",
        cogs: 389.62,
        Rating: 6.1,
    },
    {
        Date: "1/2/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 40.25,
        Quantity: 2,
        Payment: "Ewallet",
        cogs: 80.5,
        Rating: 7.8,
    },
    {
        Date: "1/3/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 30.5,
        Quantity: 6,
        Payment: "Cash",
        cogs: 183.0,
        Rating: 6.6,
    },
    {
        Date: "1/3/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 70.0,
        Quantity: 4,
        Payment: "Credit card",
        cogs: 280.0,
        Rating: 8.0,
    },
    {
        Date: "1/3/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 68.34,
        Quantity: 3,
        Payment: "Ewallet",
        cogs: 205.02,
        Rating: 7.2,
    },
    {
        Date: "1/3/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 52.1,
        Quantity: 8,
        Payment: "Cash",
        cogs: 416.8,
        Rating: 8.3,
    },
    {
        Date: "1/4/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 38.9,
        Quantity: 5,
        Payment: "Credit card",
        cogs: 194.5,
        Rating: 6.4,
    },
    {
        Date: "1/4/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 48.75,
        Quantity: 9,
        Payment: "Cash",
        cogs: 438.75,
        Rating: 7.5,
    },
    {
        Date: "1/4/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 25.4,
        Quantity: 7,
        Payment: "Ewallet",
        cogs: 177.8,
        Rating: 5.9,
    },
    {
        Date: "1/5/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 77.89,
        Quantity: 2,
        Payment: "Credit card",
        cogs: 155.78,
        Rating: 8.7,
    },
    {
        Date: "1/5/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 61.2,
        Quantity: 6,
        Payment: "Cash",
        cogs: 367.2,
        Rating: 7.1,
    },
    {
        Date: "1/5/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 56.8,
        Quantity: 4,
        Payment: "Ewallet",
        cogs: 227.2,
        Rating: 8.6,
    },
    {
        Date: "1/6/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 42.15,
        Quantity: 10,
        Payment: "Credit card",
        cogs: 421.5,
        Rating: 6.8,
    },
    {
        Date: "1/6/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 33.9,
        Quantity: 5,
        Payment: "Cash",
        cogs: 169.5,
        Rating: 7.3,
    },
    {
        Date: "1/6/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 82.5,
        Quantity: 1,
        Payment: "Ewallet",
        cogs: 82.5,
        Rating: 9.0,
    },
    {
        Date: "1/7/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 28.99,
        Quantity: 8,
        Payment: "Credit card",
        cogs: 231.92,
        Rating: 6.5,
    },
    {
        Date: "1/7/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 69.8,
        Quantity: 3,
        Payment: "Cash",
        cogs: 209.4,
        Rating: 8.1,
    },
    {
        Date: "1/7/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 49.5,
        Quantity: 7,
        Payment: "Ewallet",
        cogs: 346.5,
        Rating: 7.9,
    },
    {
        Date: "1/8/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 44.3,
        Quantity: 6,
        Payment: "Credit card",
        cogs: 265.8,
        Rating: 6.2,
    },
    {
        Date: "1/8/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 39.75,
        Quantity: 9,
        Payment: "Cash",
        cogs: 357.75,
        Rating: 7.6,
    },
    {
        Date: "1/8/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 22.8,
        Quantity: 10,
        Payment: "Ewallet",
        cogs: 228.0,
        Rating: 5.5,
    },
    {
        Date: "1/9/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 73.45,
        Quantity: 4,
        Payment: "Credit card",
        cogs: 293.8,
        Rating: 8.4,
    },
    {
        Date: "1/9/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 66.1,
        Quantity: 5,
        Payment: "Cash",
        cogs: 330.5,
        Rating: 7.0,
    },
    {
        Date: "1/9/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 51.2,
        Quantity: 2,
        Payment: "Ewallet",
        cogs: 102.4,
        Rating: 8.8,
    },
    {
        Date: "1/10/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 46.7,
        Quantity: 8,
        Payment: "Credit card",
        cogs: 373.6,
        Rating: 6.3,
    },
    {
        Date: "1/10/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 35.5,
        Quantity: 7,
        Payment: "Cash",
        cogs: 248.5,
        Rating: 7.4,
    },
    {
        Date: "1/10/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 27.3,
        Quantity: 6,
        Payment: "Ewallet",
        cogs: 163.8,
        Rating: 5.8,
    },
    {
        Date: "1/11/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 80.0,
        Quantity: 3,
        Payment: "Credit card",
        cogs: 240.0,
        Rating: 8.9,
    },
    {
        Date: "1/11/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 63.4,
        Quantity: 4,
        Payment: "Cash",
        cogs: 253.6,
        Rating: 7.2,
    },
    {
        Date: "1/11/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 53.6,
        Quantity: 5,
        Payment: "Ewallet",
        cogs: 268.0,
        Rating: 8.5,
    },
    {
        Date: "1/12/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 41.8,
        Quantity: 9,
        Payment: "Credit card",
        cogs: 376.2,
        Rating: 6.0,
    },
    {
        Date: "1/12/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 32.9,
        Quantity: 10,
        Payment: "Cash",
        cogs: 329.0,
        Rating: 7.7,
    },
    {
        Date: "1/12/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 24.5,
        Quantity: 8,
        Payment: "Ewallet",
        cogs: 196.0,
        Rating: 5.6,
    },
    {
        Date: "1/13/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 85.2,
        Quantity: 2,
        Payment: "Credit card",
        cogs: 170.4,
        Rating: 9.2,
    },
    {
        Date: "1/13/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 67.5,
        Quantity: 6,
        Payment: "Cash",
        cogs: 405.0,
        Rating: 7.3,
    },
    {
        Date: "1/13/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 50.1,
        Quantity: 3,
        Payment: "Ewallet",
        cogs: 150.3,
        Rating: 8.6,
    },
    {
        Date: "1/14/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 43.7,
        Quantity: 7,
        Payment: "Credit card",
        cogs: 305.9,
        Rating: 6.1,
    },
    {
        Date: "1/14/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 37.2,
        Quantity: 4,
        Payment: "Cash",
        cogs: 148.8,
        Rating: 7.5,
    },
    {
        Date: "1/14/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 26.8,
        Quantity: 9,
        Payment: "Ewallet",
        cogs: 241.2,
        Rating: 5.7,
    },
    {
        Date: "1/15/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 76.3,
        Quantity: 5,
        Payment: "Credit card",
        cogs: 381.5,
        Rating: 8.3,
    },
    {
        Date: "1/15/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 60.9,
        Quantity: 8,
        Payment: "Cash",
        cogs: 487.2,
        Rating: 7.1,
    },
    {
        Date: "1/15/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 54.4,
        Quantity: 1,
        Payment: "Ewallet",
        cogs: 54.4,
        Rating: 8.7,
    },
    {
        Date: "1/16/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 45.5,
        Quantity: 10,
        Payment: "Credit card",
        cogs: 455.0,
        Rating: 6.4,
    },
    {
        Date: "1/16/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 31.6,
        Quantity: 6,
        Payment: "Cash",
        cogs: 189.6,
        Rating: 7.8,
    },
    {
        Date: "1/16/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 23.9,
        Quantity: 5,
        Payment: "Ewallet",
        cogs: 119.5,
        Rating: 6.0,
    },
    {
        Date: "1/17/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 88.1,
        Quantity: 3,
        Payment: "Credit card",
        cogs: 264.3,
        Rating: 9.0,
    },
    {
        Date: "1/17/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 64.3,
        Quantity: 7,
        Payment: "Cash",
        cogs: 450.1,
        Rating: 7.6,
    },
    {
        Date: "1/17/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 47.8,
        Quantity: 4,
        Payment: "Ewallet",
        cogs: 191.2,
        Rating: 8.2,
    },
    {
        Date: "1/18/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 40.4,
        Quantity: 9,
        Payment: "Credit card",
        cogs: 363.6,
        Rating: 6.2,
    },
    {
        Date: "1/18/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 34.1,
        Quantity: 8,
        Payment: "Cash",
        cogs: 272.8,
        Rating: 7.4,
    },
    {
        Date: "1/18/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 20.5,
        Quantity: 10,
        Payment: "Ewallet",
        cogs: 205.0,
        Rating: 5.4,
    },
    {
        Date: "1/19/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 79.6,
        Quantity: 2,
        Payment: "Credit card",
        cogs: 159.2,
        Rating: 8.8,
    },
    {
        Date: "1/19/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 62.0,
        Quantity: 5,
        Payment: "Cash",
        cogs: 310.0,
        Rating: 7.0,
    },
    {
        Date: "1/19/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 55.7,
        Quantity: 6,
        Payment: "Ewallet",
        cogs: 334.2,
        Rating: 8.5,
    },
    {
        Date: "1/20/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 39.2,
        Quantity: 7,
        Payment: "Credit card",
        cogs: 274.4,
        Rating: 6.3,
    },
    {
        Date: "1/20/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 36.4,
        Quantity: 3,
        Payment: "Cash",
        cogs: 109.2,
        Rating: 7.5,
    },
    {
        Date: "1/20/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 21.7,
        Quantity: 9,
        Payment: "Ewallet",
        cogs: 195.3,
        Rating: 5.8,
    },
    {
        Date: "1/21/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 72.8,
        Quantity: 4,
        Payment: "Credit card",
        cogs: 291.2,
        Rating: 8.1,
    },
    {
        Date: "1/21/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 65.5,
        Quantity: 6,
        Payment: "Cash",
        cogs: 393.0,
        Rating: 7.2,
    },
    {
        Date: "1/21/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 48.3,
        Quantity: 8,
        Payment: "Ewallet",
        cogs: 386.4,
        Rating: 8.4,
    },
    {
        Date: "1/22/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 42.9,
        Quantity: 5,
        Payment: "Credit card",
        cogs: 214.5,
        Rating: 6.5,
    },
    {
        Date: "1/22/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 30.8,
        Quantity: 10,
        Payment: "Cash",
        cogs: 308.0,
        Rating: 7.6,
    },
    {
        Date: "1/22/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 19.9,
        Quantity: 7,
        Payment: "Ewallet",
        cogs: 139.3,
        Rating: 5.3,
    },
    {
        Date: "1/23/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 81.5,
        Quantity: 3,
        Payment: "Credit card",
        cogs: 244.5,
        Rating: 8.9,
    },
    {
        Date: "1/23/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 59.6,
        Quantity: 9,
        Payment: "Cash",
        cogs: 536.4,
        Rating: 7.3,
    },
    {
        Date: "1/23/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 53.0,
        Quantity: 2,
        Payment: "Ewallet",
        cogs: 106.0,
        Rating: 8.6,
    },
    {
        Date: "1/24/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 44.8,
        Quantity: 8,
        Payment: "Credit card",
        cogs: 358.4,
        Rating: 6.7,
    },
    {
        Date: "1/24/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 33.2,
        Quantity: 6,
        Payment: "Cash",
        cogs: 199.2,
        Rating: 7.9,
    },
    {
        Date: "1/24/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 22.1,
        Quantity: 5,
        Payment: "Ewallet",
        cogs: 110.5,
        Rating: 5.9,
    },
    {
        Date: "1/25/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 83.7,
        Quantity: 4,
        Payment: "Credit card",
        cogs: 334.8,
        Rating: 9.1,
    },
    {
        Date: "1/25/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 68.4,
        Quantity: 7,
        Payment: "Cash",
        cogs: 478.8,
        Rating: 7.4,
    },
    {
        Date: "1/25/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 51.9,
        Quantity: 3,
        Payment: "Ewallet",
        cogs: 155.7,
        Rating: 8.3,
    },
    {
        Date: "1/26/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 37.6,
        Quantity: 10,
        Payment: "Credit card",
        cogs: 376.0,
        Rating: 6.0,
    },
    {
        Date: "1/26/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 35.3,
        Quantity: 4,
        Payment: "Cash",
        cogs: 141.2,
        Rating: 7.7,
    },
    {
        Date: "1/26/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 23.4,
        Quantity: 8,
        Payment: "Ewallet",
        cogs: 187.2,
        Rating: 5.5,
    },
    {
        Date: "1/27/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Electronic accessories",
        "Unit price": 75.0,
        Quantity: 5,
        Payment: "Credit card",
        cogs: 375.0,
        Rating: 8.5,
    },
    {
        Date: "1/27/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Fashion accessories",
        "Unit price": 66.9,
        Quantity: 6,
        Payment: "Cash",
        cogs: 401.4,
        Rating: 7.1,
    },
    {
        Date: "1/27/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Health and beauty",
        "Unit price": 50.3,
        Quantity: 9,
        Payment: "Ewallet",
        cogs: 452.7,
        Rating: 8.7,
    },
    {
        Date: "1/28/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Home and lifestyle",
        "Unit price": 41.1,
        Quantity: 7,
        Payment: "Credit card",
        cogs: 287.7,
        Rating: 6.2,
    },
    {
        Date: "1/28/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Female",
        "Product line": "Sports and travel",
        "Unit price": 32.7,
        Quantity: 5,
        Payment: "Cash",
        cogs: 163.5,
        Rating: 7.5,
    },
    {
        Date: "1/28/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Male",
        "Product line": "Food and beverages",
        "Unit price": 25.6,
        Quantity: 6,
        Payment: "Ewallet",
        cogs: 153.6,
        Rating: 5.7,
    },
    {
        Date: "1/29/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Electronic accessories",
        "Unit price": 87.2,
        Quantity: 2,
        Payment: "Credit card",
        cogs: 174.4,
        Rating: 9.0,
    },
    {
        Date: "1/29/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Fashion accessories",
        "Unit price": 64.8,
        Quantity: 8,
        Payment: "Cash",
        cogs: 518.4,
        Rating: 7.2,
    },
    {
        Date: "1/29/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Health and beauty",
        "Unit price": 52.5,
        Quantity: 4,
        Payment: "Ewallet",
        cogs: 210.0,
        Rating: 8.4,
    },
    {
        Date: "1/30/2019",
        Branch: "A",
        City: "Yangon",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Home and lifestyle",
        "Unit price": 43.0,
        Quantity: 9,
        Payment: "Credit card",
        cogs: 387.0,
        Rating: 6.3,
    },
    {
        Date: "1/30/2019",
        Branch: "B",
        City: "Mandalay",
        "Customer type": "Member",
        Gender: "Male",
        "Product line": "Sports and travel",
        "Unit price": 34.9,
        Quantity: 3,
        Payment: "Cash",
        cogs: 104.7,
        Rating: 7.6,
    },
    {
        Date: "1/30/2019",
        Branch: "C",
        City: "Naypyitaw",
        "Customer type": "Normal",
        Gender: "Female",
        "Product line": "Food and beverages",
        "Unit price": 21.3,
        Quantity: 10,
        Payment: "Ewallet",
        cogs: 213.0,
        Rating: 5.6,
    },
];
